### ISSUE TITLE
I can't extract checkpoint.tar

### ISSUE THREAD

**Issue by yangfeifan-ufo** [Lonepic/SPIB#2]
I can't extract checkpoint.tar,can you send the zip or original files to my address:  1653669244@qq.com
respect!
![image](https://user-images.githubusercontent.com/62707819/187032727-ec0d4087-f006-4e6a-872e-fff02fb3ef55.png)

**Comment by Lonepic** [comment]
这个不是让你用解压软件解压出来的呀，这个是用torch.load()载入模型权重的时候用的
